import Head from "next/head";
import Image from "next/image";
import imageLoader from "@/components/imageLoader";
import { GetStaticProps, NextPage } from "next";
import { GetCharacterResults, Character } from "@/types";

type Props = {
  characters: Character[];
};

const Home: NextPage<Props> = ({ characters }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full mx-auto grid grid-cols-3 justify-center items-center">
        {characters.map((char) => {
          return (
            <div
              key={char.id}
              className="flex flex-col justify-center items-center"
            >
              {char.name}
              <Image
                loader={imageLoader}
                src={char.image}
                alt={char.name}
                width="200"
                height="200"
              />
            </div>
          );
        })}
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { results }: GetCharacterResults = await res.json();

  return {
    props: {
      characters: results,
    },
  };
};

export default Home;
